version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - network-desafio
    volumes:
      - mysql_data:/var/lib/mysql

  api-desafio:
    build:
      context: .
    container_name: api-desafio
    ports:
      - 3001:${APP_PORT}
    depends_on:
      - mysql
    networks:
      - network-desafio
    env_file:
      - .env

networks:
  network-desafio:
    driver: bridge

volumes:
  mysql_data: